### ISSUE TITLE
Rounded Corner Patch

### ISSUE THREAD

**Issue by sayan01** [igor37/dwm-rounded-corners#2]
Can you provide the patch file for the rounded corners. I would like rounded corners but on my own dwm fork. For that having the patch file would be great.

**Comment by sayan01** [comment]
by patch i mean the patch of only rounded. as the rest are already available online, and the combined patch is already in the repo.

**Comment by whyvn** [comment]
You can `git diff` from the original dwm 6.2 but i couldnt find an original official download maybe youll have more luck. Though you can just manually patch it yourself by addign refrences and definitions of the [roundcorners](https://github.com/igor37/dwm-rounded-corners/blob/master/dwm.c#L2283) function in [dwm.c](https://raw.githubusercontent.com/igor37/dwm-rounded-corners/master/dwm.c)

**Comment by sayan01** [comment]
nevermind i was looking for the wrong thing, its way easier to round corners via the compositor (picom). Thank you.
